language: node_js
node_js: '10'
cache: yarn
before_install:
- echo "//registry.npmjs.org/:_authToken=\$NPM_TOKEN" > ~/.npmrc
script:
- yarn ci
deploy:
  provider: npm
  skip_cleanup: true
  email: rishabhsrao@gmail.com
  api_key:
    secure: oem5lNXOYWzqluaoIdPYPCcCIqkNp88oV/mQ82zM3jmEFdRJZxMm49oxYtVAFVQ0QOgyuWvxDWZaAthyYfA6Y632pnlf/4vii07/QGLiySe0pGWtJo4D+slM9RTL8m/pQqeuRqpQdJURFLxH4gx+1kLDAnW2ebRHWCzL+QNIFVOCz+p2ouO4/j3UrsMw3OHbbt9dYzRYIkHdYAYnL0L/Ya77AdR189LV6c0H11cZRi5azYx+COKXajaz8NWw9UA93Ne7gFWdaVVbHa/cSbazRbccgxyErhaeUCCABLR+RSO7vnfrzgOSXaOIkvJz0zVtGh112ABa8sT2fEuR7q/naE0JcP741xj59h+ef8zpOBjbjpCYn32gXzhECOQhlPLNfXITcNZEPPR5+c9XLriqsxh0dg56XZFpfTex1J/Pg1mK7zzcSQqKq1XJnsyr03igeE4eVprq1FjDbvZhSmZhUm0r54HH6UUuBq+OZg9M8CmeQZSGMj0Var0QRlc6QQzgbNOgHPuocCImSCN8fwjSRnWnnQk/SWbGD1hDNtvnWWiGY0xPNpPO7pUj6HjZ8Lw4qc3R2nUEB88Vrj+bEnYhWW8CboSBNW8h/AllyQJ7t2UEjZ4R4XLCBIkGL62IHuv6QmrhSh+D3kDLhVZaRU7drLhkZ2KCvodocbEt6od0wd8=
  on:
    tags: true
