language: node_js
node_js: '10'
cache: yarn
before_install:
- echo "//registry.npmjs.org/:_authToken=\$NPM_TOKEN" > ~/.npmrc
script:
- yarn ci
deploy:
  provider: npm
  skip_cleanup: true
  email: rishabhsrao@gmail.com
  api_key:
    secure: Elx+U7KxjBlxJJjyN+h83CuUv9Xh8Llsun30snq8elwnhJXqmx9mNxsxhveJDiUVeRn6ZKaA7Ilz5vyixmvuPoEhVvsHR6Mp58QWmCMM/kgaxN0ZGPSnVT52nR1qLgpa9xjW4AFvOwR6Cl//YzIi7mKj01rEfvIxLK8uNaZv6EgMdzFo8pBpMh0A86svknQvEcshZm88daftegEDLUmc47j1h1FkagTATPMYAkHkrOWPvlAgE50fgggqD5qzCjcxLJNRIcSiZzNg684+Ek20buv35KXnrKu2rPmq8GQ6Mnun90PYrGakulxQDMXZWR3tRpZLkJOBI2kYLF+4fnlyck/eBtyJnW6kZ4N4yIF43wLnD686s/HQPDHlNSgaf0SqJpDnLx2QY1Dfzs7HTXtdbnzTHTb9cQiDc7wbVoLu5dXmWs9YRGAO1WioNhtcTDeSE30m5KOWdJkebZUhHpouqSrjQLe82wpba88Qp+LIHryldfNe4VRzemHphRqnhlm/nbs3wng+5H6uFqGH6Nn0IkAmbaJRAz+cusB+uNshWeT33MO55aOJkWgbHH91W77QCNMUMHx+rg2i5nChgTJU2LKCrvOoSZr1yGsBZYHzCB0Og3htp+4rUqs+NgZcgvU8Ct3ENlf+vum8ZAODfjpbGdyyzugHvFSwvPLdAULqd4Q=
  on:
    tags: true
