name: Test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@magica11y'

      - name: Install dependencies
        id: install
        run: yarn install

      - name: Lint
        id: lint
        run: yarn lint

      - name: Typecheck
        id: typecheck
        run: yarn typecheck

      - name: Test
        id: test
        run: yarn test
