# See https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-nodejs-packages#publishing-packages-using-yarn

name: Run tests on main
on:
  push:
env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@magica11y'
      - run: yarn
      - run: yarn test:coverage
